import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import Navbar from '@/app/__components__/navbar';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={inter.className} suppressHydrationWarning>
				<Navbar />
				{children}
				<div
					id="terminal-portal"
					className="fixed bottom-8 right-2 flex h-full flex-col-reverse gap-1 lg:bottom-10 lg:right-5"
				></div>
			</body>
		</html>
	);
}
