/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'

// Create Virtual Routes

const TestLazyImport = createFileRoute('/test')()
const SomeOnScrollTextHighlightAnimationsLazyImport = createFileRoute(
  '/some-on-scroll-text-highlight-animations',
)()
const OnScrollExpandingImageAnimationWithinTypographyLazyImport =
  createFileRoute('/on-scroll-expanding-image-animation-within-typography')()
const OnScroll3dCarouselLazyImport = createFileRoute('/on-scroll-3d-carousel')()
const LenisScaleAndPinLazyImport = createFileRoute('/lenis-scale-and-pin')()
const HelloLazyImport = createFileRoute('/hello')()
const ConsecutiveScrollAnimationsWithOneElementLazyImport = createFileRoute(
  '/consecutive-scroll-animations-with-one-element',
)()
const BlurryTextRevealOnScrollLazyImport = createFileRoute(
  '/blurry-text-reveal-on-scroll',
)()

// Create/Update Routes

const TestLazyRoute = TestLazyImport.update({
  id: '/test',
  path: '/test',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/test.lazy').then((d) => d.Route))

const SomeOnScrollTextHighlightAnimationsLazyRoute =
  SomeOnScrollTextHighlightAnimationsLazyImport.update({
    id: '/some-on-scroll-text-highlight-animations',
    path: '/some-on-scroll-text-highlight-animations',
    getParentRoute: () => rootRoute,
  } as any).lazy(() =>
    import('./routes/some-on-scroll-text-highlight-animations.lazy').then(
      (d) => d.Route,
    ),
  )

const OnScrollExpandingImageAnimationWithinTypographyLazyRoute =
  OnScrollExpandingImageAnimationWithinTypographyLazyImport.update({
    id: '/on-scroll-expanding-image-animation-within-typography',
    path: '/on-scroll-expanding-image-animation-within-typography',
    getParentRoute: () => rootRoute,
  } as any).lazy(() =>
    import(
      './routes/on-scroll-expanding-image-animation-within-typography.lazy'
    ).then((d) => d.Route),
  )

const OnScroll3dCarouselLazyRoute = OnScroll3dCarouselLazyImport.update({
  id: '/on-scroll-3d-carousel',
  path: '/on-scroll-3d-carousel',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/on-scroll-3d-carousel.lazy').then((d) => d.Route),
)

const LenisScaleAndPinLazyRoute = LenisScaleAndPinLazyImport.update({
  id: '/lenis-scale-and-pin',
  path: '/lenis-scale-and-pin',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/lenis-scale-and-pin.lazy').then((d) => d.Route),
)

const HelloLazyRoute = HelloLazyImport.update({
  id: '/hello',
  path: '/hello',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/hello.lazy').then((d) => d.Route))

const ConsecutiveScrollAnimationsWithOneElementLazyRoute =
  ConsecutiveScrollAnimationsWithOneElementLazyImport.update({
    id: '/consecutive-scroll-animations-with-one-element',
    path: '/consecutive-scroll-animations-with-one-element',
    getParentRoute: () => rootRoute,
  } as any).lazy(() =>
    import('./routes/consecutive-scroll-animations-with-one-element.lazy').then(
      (d) => d.Route,
    ),
  )

const BlurryTextRevealOnScrollLazyRoute =
  BlurryTextRevealOnScrollLazyImport.update({
    id: '/blurry-text-reveal-on-scroll',
    path: '/blurry-text-reveal-on-scroll',
    getParentRoute: () => rootRoute,
  } as any).lazy(() =>
    import('./routes/blurry-text-reveal-on-scroll.lazy').then((d) => d.Route),
  )

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/blurry-text-reveal-on-scroll': {
      id: '/blurry-text-reveal-on-scroll'
      path: '/blurry-text-reveal-on-scroll'
      fullPath: '/blurry-text-reveal-on-scroll'
      preLoaderRoute: typeof BlurryTextRevealOnScrollLazyImport
      parentRoute: typeof rootRoute
    }
    '/consecutive-scroll-animations-with-one-element': {
      id: '/consecutive-scroll-animations-with-one-element'
      path: '/consecutive-scroll-animations-with-one-element'
      fullPath: '/consecutive-scroll-animations-with-one-element'
      preLoaderRoute: typeof ConsecutiveScrollAnimationsWithOneElementLazyImport
      parentRoute: typeof rootRoute
    }
    '/hello': {
      id: '/hello'
      path: '/hello'
      fullPath: '/hello'
      preLoaderRoute: typeof HelloLazyImport
      parentRoute: typeof rootRoute
    }
    '/lenis-scale-and-pin': {
      id: '/lenis-scale-and-pin'
      path: '/lenis-scale-and-pin'
      fullPath: '/lenis-scale-and-pin'
      preLoaderRoute: typeof LenisScaleAndPinLazyImport
      parentRoute: typeof rootRoute
    }
    '/on-scroll-3d-carousel': {
      id: '/on-scroll-3d-carousel'
      path: '/on-scroll-3d-carousel'
      fullPath: '/on-scroll-3d-carousel'
      preLoaderRoute: typeof OnScroll3dCarouselLazyImport
      parentRoute: typeof rootRoute
    }
    '/on-scroll-expanding-image-animation-within-typography': {
      id: '/on-scroll-expanding-image-animation-within-typography'
      path: '/on-scroll-expanding-image-animation-within-typography'
      fullPath: '/on-scroll-expanding-image-animation-within-typography'
      preLoaderRoute: typeof OnScrollExpandingImageAnimationWithinTypographyLazyImport
      parentRoute: typeof rootRoute
    }
    '/some-on-scroll-text-highlight-animations': {
      id: '/some-on-scroll-text-highlight-animations'
      path: '/some-on-scroll-text-highlight-animations'
      fullPath: '/some-on-scroll-text-highlight-animations'
      preLoaderRoute: typeof SomeOnScrollTextHighlightAnimationsLazyImport
      parentRoute: typeof rootRoute
    }
    '/test': {
      id: '/test'
      path: '/test'
      fullPath: '/test'
      preLoaderRoute: typeof TestLazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/blurry-text-reveal-on-scroll': typeof BlurryTextRevealOnScrollLazyRoute
  '/consecutive-scroll-animations-with-one-element': typeof ConsecutiveScrollAnimationsWithOneElementLazyRoute
  '/hello': typeof HelloLazyRoute
  '/lenis-scale-and-pin': typeof LenisScaleAndPinLazyRoute
  '/on-scroll-3d-carousel': typeof OnScroll3dCarouselLazyRoute
  '/on-scroll-expanding-image-animation-within-typography': typeof OnScrollExpandingImageAnimationWithinTypographyLazyRoute
  '/some-on-scroll-text-highlight-animations': typeof SomeOnScrollTextHighlightAnimationsLazyRoute
  '/test': typeof TestLazyRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/blurry-text-reveal-on-scroll': typeof BlurryTextRevealOnScrollLazyRoute
  '/consecutive-scroll-animations-with-one-element': typeof ConsecutiveScrollAnimationsWithOneElementLazyRoute
  '/hello': typeof HelloLazyRoute
  '/lenis-scale-and-pin': typeof LenisScaleAndPinLazyRoute
  '/on-scroll-3d-carousel': typeof OnScroll3dCarouselLazyRoute
  '/on-scroll-expanding-image-animation-within-typography': typeof OnScrollExpandingImageAnimationWithinTypographyLazyRoute
  '/some-on-scroll-text-highlight-animations': typeof SomeOnScrollTextHighlightAnimationsLazyRoute
  '/test': typeof TestLazyRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/blurry-text-reveal-on-scroll': typeof BlurryTextRevealOnScrollLazyRoute
  '/consecutive-scroll-animations-with-one-element': typeof ConsecutiveScrollAnimationsWithOneElementLazyRoute
  '/hello': typeof HelloLazyRoute
  '/lenis-scale-and-pin': typeof LenisScaleAndPinLazyRoute
  '/on-scroll-3d-carousel': typeof OnScroll3dCarouselLazyRoute
  '/on-scroll-expanding-image-animation-within-typography': typeof OnScrollExpandingImageAnimationWithinTypographyLazyRoute
  '/some-on-scroll-text-highlight-animations': typeof SomeOnScrollTextHighlightAnimationsLazyRoute
  '/test': typeof TestLazyRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/blurry-text-reveal-on-scroll'
    | '/consecutive-scroll-animations-with-one-element'
    | '/hello'
    | '/lenis-scale-and-pin'
    | '/on-scroll-3d-carousel'
    | '/on-scroll-expanding-image-animation-within-typography'
    | '/some-on-scroll-text-highlight-animations'
    | '/test'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/blurry-text-reveal-on-scroll'
    | '/consecutive-scroll-animations-with-one-element'
    | '/hello'
    | '/lenis-scale-and-pin'
    | '/on-scroll-3d-carousel'
    | '/on-scroll-expanding-image-animation-within-typography'
    | '/some-on-scroll-text-highlight-animations'
    | '/test'
  id:
    | '__root__'
    | '/'
    | '/blurry-text-reveal-on-scroll'
    | '/consecutive-scroll-animations-with-one-element'
    | '/hello'
    | '/lenis-scale-and-pin'
    | '/on-scroll-3d-carousel'
    | '/on-scroll-expanding-image-animation-within-typography'
    | '/some-on-scroll-text-highlight-animations'
    | '/test'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BlurryTextRevealOnScrollLazyRoute: typeof BlurryTextRevealOnScrollLazyRoute
  ConsecutiveScrollAnimationsWithOneElementLazyRoute: typeof ConsecutiveScrollAnimationsWithOneElementLazyRoute
  HelloLazyRoute: typeof HelloLazyRoute
  LenisScaleAndPinLazyRoute: typeof LenisScaleAndPinLazyRoute
  OnScroll3dCarouselLazyRoute: typeof OnScroll3dCarouselLazyRoute
  OnScrollExpandingImageAnimationWithinTypographyLazyRoute: typeof OnScrollExpandingImageAnimationWithinTypographyLazyRoute
  SomeOnScrollTextHighlightAnimationsLazyRoute: typeof SomeOnScrollTextHighlightAnimationsLazyRoute
  TestLazyRoute: typeof TestLazyRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BlurryTextRevealOnScrollLazyRoute: BlurryTextRevealOnScrollLazyRoute,
  ConsecutiveScrollAnimationsWithOneElementLazyRoute:
    ConsecutiveScrollAnimationsWithOneElementLazyRoute,
  HelloLazyRoute: HelloLazyRoute,
  LenisScaleAndPinLazyRoute: LenisScaleAndPinLazyRoute,
  OnScroll3dCarouselLazyRoute: OnScroll3dCarouselLazyRoute,
  OnScrollExpandingImageAnimationWithinTypographyLazyRoute:
    OnScrollExpandingImageAnimationWithinTypographyLazyRoute,
  SomeOnScrollTextHighlightAnimationsLazyRoute:
    SomeOnScrollTextHighlightAnimationsLazyRoute,
  TestLazyRoute: TestLazyRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/blurry-text-reveal-on-scroll",
        "/consecutive-scroll-animations-with-one-element",
        "/hello",
        "/lenis-scale-and-pin",
        "/on-scroll-3d-carousel",
        "/on-scroll-expanding-image-animation-within-typography",
        "/some-on-scroll-text-highlight-animations",
        "/test"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/blurry-text-reveal-on-scroll": {
      "filePath": "blurry-text-reveal-on-scroll.lazy.tsx"
    },
    "/consecutive-scroll-animations-with-one-element": {
      "filePath": "consecutive-scroll-animations-with-one-element.lazy.tsx"
    },
    "/hello": {
      "filePath": "hello.lazy.tsx"
    },
    "/lenis-scale-and-pin": {
      "filePath": "lenis-scale-and-pin.lazy.tsx"
    },
    "/on-scroll-3d-carousel": {
      "filePath": "on-scroll-3d-carousel.lazy.tsx"
    },
    "/on-scroll-expanding-image-animation-within-typography": {
      "filePath": "on-scroll-expanding-image-animation-within-typography.lazy.tsx"
    },
    "/some-on-scroll-text-highlight-animations": {
      "filePath": "some-on-scroll-text-highlight-animations.lazy.tsx"
    },
    "/test": {
      "filePath": "test.lazy.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
